CepMvcApp.Main/Models/CepViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CepMvcApp.Main.Models
{
    public class CepViewModel
    {
        public CepViewModel() {;}

        public long ID { get; set; }

        [Display(Name = "CEP")]
        [Required(ErrorMessage = "Por favor preencha o CEP")]
        [StringLength(9, MinimumLength = 8, ErrorMessage = "CEP inválido")]
        [RegularExpression("([0-9-]*$)", ErrorMessage = "CEP inválido")]
        public string Valor { get; set; }

        [Display(Name = "Código IBGE")]
        [Required(ErrorMessage = "Por favor preencha o Código IBGE")]
        [RegularExpression("([0-9]{7})", ErrorMessage = "Código IBGE inválido")]
        public string CodigoIBGE { get; set; }

        public string NomeUnidadeFederativa { get; set; }
        public string NomeLocalidade { get; set; }
        public string NomeBairro { get; set; }


        [Display(Name = "Logradouro")]
        [StringLength(150, MinimumLength = 0, ErrorMessage = "Logradouro inválido")]
        public string Logradouro { get; set; }

        [Display(Name = "Complemento")]
        [StringLength(150, MinimumLength = 0, ErrorMessage = "Complemento inválido")]
        public string Complemento { get; set; }
        

        [Display(Name = "Gia")]
        [StringLength(10, MinimumLength = 1, ErrorMessage = "Gia inválido")]
        [RegularExpression("([0-9]{1,10})", ErrorMessage = "Gia inválido")]
        public string Gia { get; set; }

        [Display(Name = "Siafi")]
        [RegularExpression("^[0-9]{1,10}$", ErrorMessage = "Siafi inválido")]
        public string Siafi { get; set; }

        [Display(Name = "Data Cadastro")]
        [DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}", ApplyFormatInEditMode = true)]
        //[DataType(DataType.DateTime, ErrorMessage = "Formato de Data Invalido")]
        public string DataCadastro { get; set; }

        [Required]
        [Display(Name = "Unidade Federativa")]
        [Range(1, long.MaxValue, ErrorMessage = "Por favor selecione a Unidade Federativa")]
        public long IDUnidadeFederativa { get; set; }

        [Required]
        [Display(Name = "Localidade")]
        [Range(1, long.MaxValue, ErrorMessage = "Por favor selecione a Localidade")]
        public long IDLocalidade { get; set; }

        [Display(Name = "Bairro")]
        [Range(1, long.MaxValue, ErrorMessage = "Por favor selecione o Bairro")]
        public long? IDBairro { get; set; }


        [Required]
        [Display(Name = "DDD")]
        [Range(1, long.MaxValue, ErrorMessage = "Por favor selecione o DDD")]
        public long IDDiscagemDiretaDistancia { get; set; }
    }
}

CepMvcApp.Main/Controllers/CepController.cs
using System.Text;
using System.Web.Mvc;
using System.Linq;
using System.Data.Entity;
using System.Net;
using CepMvcApp.Data;
using CepMvcApp.Main.Models;
using CepMvcApp.Model;

namespace CepMvcApp.Main.Controllers
{
    public class CepController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult List()
        {
            /* TODO: não é papel do Controller acessar *
             * diretamente a camada de persistência!   */
            using (var db = new EntitiesDbContext())
            {
                var data =   db.CodigosEnderecamentoPostal
                            .ToList()
                            .Select(d => new CepViewModel()
                            {
                                ID = d.ID,
                                Valor = d.Valor,
                                CodigoIBGE = d._LocalidadesIBGE.CodigoIBGE,
                                NomeUnidadeFederativa = d._UnidadesFederativas.Nome,
                                NomeLocalidade = d._LocalidadesIBGE.Nome,
                                NomeBairro = d._Bairros != null ? d._Bairros.Nome : "",
                                Logradouro = d.Logradouro,
                                Complemento = d.Complemento
                            })
                            .ToList();

                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult GetDadosBuscadorCep(long cep)
        {
            using (var webClient = new WebClient() { Encoding = Encoding.UTF8 })
            {
                var urlConsulta = $"https://viacep.com.br/ws/{cep}/json/";
                var json = webClient.DownloadString(urlConsulta);

                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Form(long id)
        {
            CepViewModel cepViewModel = null;
            if (id == 0)
            {
                cepViewModel = new CepViewModel();
            }
            else
            {
                using (var db = new EntitiesDbContext())
                {
                    var dados = db.CodigosEnderecamentoPostal.Find(id);

                    cepViewModel = new CepViewModel()
                    {
                        Valor = dados.Valor,
                        CodigoIBGE = dados._LocalidadesIBGE.CodigoIBGE,
                        Logradouro = dados.Logradouro,
                        Complemento = dados.Complemento,
                        Gia = dados._LocalidadesIBGE.Gia,
                        Siafi = dados._LocalidadesIBGE.Siafi,
                        IDBairro = dados.IDBairro,
                        IDLocalidade = dados.IDLocalidade,
                        IDUnidadeFederativa = dados.IDUnidadeFederativa,
                        IDDiscagemDiretaDistancia = dados.IDDiscagemDiretaDistancia,
                    };
                }
            }

            return View(cepViewModel);
        }

        [HttpPost]
        public ActionResult SalvarForm(CepViewModel dados)
        {
            using (var db = new EntitiesDbContext())
            {
                var cep = db.CodigosEnderecamentoPostal.Find(dados.ID);

                bool estahEditando = cep != null;
                if (estahEditando)
                {
                    cep.Logradouro = dados.Logradouro;
                    cep.Complemento = dados.Complemento;
                    cep.IDBairro = dados.IDBairro;
                    cep.IDLocalidade = dados.IDLocalidade;
                    cep.IDUnidadeFederativa = dados.IDUnidadeFederativa;
                    cep.IDDiscagemDiretaDistancia = dados.IDDiscagemDiretaDistancia;
                    db.Entry(cep).State = EntityState.Modified;
                }
                else
                {
                    var novoCep = new CodigosEnderecamentoPostal()
                    {
                        Valor = dados.Valor,
                        Logradouro = dados.Logradouro,
                        Complemento = dados.Complemento,
                        IDBairro = dados.IDBairro,
                        IDLocalidade = db.LocalidadesIBGE.Single(p => p.CodigoIBGE == dados.CodigoIBGE).ID,
                        IDUnidadeFederativa = dados.IDUnidadeFederativa,
                        IDDiscagemDiretaDistancia = dados.IDDiscagemDiretaDistancia,
                    };
                    db.CodigosEnderecamentoPostal.Add(novoCep);
                }

                db.SaveChanges();
                ReturnMessage("Cep cadastrado com sucesso");
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(long id)
        {
            using (var db = new EntitiesDbContext())
            {
                var cep = db.CodigosEnderecamentoPostal.Find(id);
                db.CodigosEnderecamentoPostal.Remove(cep);

                db.SaveChanges();
                ReturnMessage("Cep excluído com sucesso");
                return RedirectToAction("Index");
            }
        }
    }
}

CepMvcApp.Main/Controllers/LocalidadeController.cs
using System;
using System.Web.Mvc;
using System.Linq;
using System.Data.Entity;
using CepMvcApp.Data;
using CepMvcApp.Main.Models;
using CepMvcApp.Model;
using System.Collections.Generic;

namespace CepMvcApp.Main.Controllers
{
    public class LocalidadeController : BaseController
    {
        public JsonResult ListDropDown (long? CodigoIBGE)
        {
            using (var db = new EntitiesDbContext())
            {
                List<LocalidadesIBGE> lista;
                var codigoIBGEConsulta = CodigoIBGE.HasValue ? CodigoIBGE.ToString() : null;
                lista = CodigoIBGE.HasValue ? db.LocalidadesIBGE.Where(item => item.CodigoIBGE == codigoIBGEConsulta).AsNoTracking().ToList()
                                            : db.LocalidadesIBGE.AsNoTracking().ToList();

                var ret = lista.Select(item => new DropDownItemViewModel { id = long.Parse(item.CodigoIBGE), text = item.Nome }).OrderBy(p => p.text).ToList();
                return Json(ret, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult SalvarViaAjax(LocalidadesViewModel dados)
        {
            using (var db = new EntitiesDbContext())
            {
                bool existe = db.LocalidadesIBGE.Any(p => p.CodigoIBGE == dados.CodigoIBGE);
                if (existe)
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }

                var novaLocalidade = new LocalidadesIBGE()
                {
                    CodigoIBGE = dados.CodigoIBGE,
                    Gia = dados.Gia,
                    Siafi = dados.Siafi,
                    Nome = dados.NomeLocalidade,
                    IDUnidadeFederativa = dados.IDUnidadeFederativa,
                    IDDiscagemDiretaDistancia = dados.IDDiscagemDiretaDistancia,
                };

                db.LocalidadesIBGE.Add(novaLocalidade);
                db.SaveChanges();
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

CepMvcApp.Main/Views/Cep/Form.cshtml
@model CepMvcApp.Main.Models.CepViewModel
@{
    ViewBag.Title = "CEP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles
{
    <link href="~/Content/plugins/select2/select2.min.css" rel="stylesheet">
}

@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/plugins/textcounter/textcounter.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/plugins/select2/select2.full.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/plugins/numeric/jquery.numeric.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/helpers/dropdown-helpers.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Views/Cep/form.js")"></script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-12">
        <h2>CEP</h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li id="aba-cadastro" class="active"><a data-toggle="tab" href="#tab-1">Cadastro</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <div class="panel panel-default">
                                <div class="panel-heading" data-spy="affix" data-offset-top="131">
                                    <a data-toggle="tab" href="#">
                                        <input type="button" value="Salvar" class="btn btn-primary" style="margin-right: 20px" onclick="salvarCadastro()" />
                                    </a>
                                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-white" })
                                </div>
                                <div class="panel-body">
                                    @using (Html.BeginForm("SalvarForm", "Cep", FormMethod.Post, new { @id = "form-cadastro" }))
                                    {
                                    <div class="form-horizontal">

                                        @Html.HiddenFor(model => model.ID, new { @id = "id" })


                                        @if (String.IsNullOrWhiteSpace(Model.Valor))
                                        {
                                            <div class="form-group">
                                                <div class="col-md-2"></div>
                                                <div class="col-md-10">
                                                    <input type="text" placeholder="_____-___" id="buscacep" class="buscacep form-control" />
                                                </div>
                                                <div class="col-md-2"></div>
                                                <div class="col-md-10">
                                                    <input type="button" data-url="@Url.Action("GetDadosBuscadorCep", "Cep", null, Request.Url.Scheme)" value="Consultar CEP" id="btn-buscacep" class="btn btn-primary fa fa-search" />
                                                </div>
                                            </div>
                                        }


                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Valor, new { @class = "lbcep control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.Valor, new { @readonly = true, placeholder = "_____-___", Value = Model.Valor, @id = "cep", @class = "cep form-control" })
                                                @Html.ValidationMessageFor(model => model.Valor)
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.CodigoIBGE, new { @class = "lbcodigoibge control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.CodigoIBGE, new { Value = Model.CodigoIBGE, @id = "codigoibge", @class = "codigoibge form-control" })
                                                @Html.ValidationMessageFor(model => model.CodigoIBGE)
                                            </div>
                                        </div>

                                        <div class="form-group hidden">
                                            @Html.LabelFor(model => model.IDUnidadeFederativa, new { @class = "lbunidadefederativva control-label col-md-2" })
                                            <div class="col-md-10">
                                                <select id="unidadefederativa" name="idUnidadeFederativa" ajax-url=@Url.Action("ListDropDown", "UnidadeFederativa", null, Request.Url.Scheme) value=@Model.IDUnidadeFederativa></select>
                                                @Html.HiddenFor(model => model.IDUnidadeFederativa, new { Value = Model.IDUnidadeFederativa, @id = "valorIdUnidadeFederativa" })
                                                @Html.ValidationMessageFor(model => model.IDUnidadeFederativa)
                                            </div>
                                        </div>

                                        <div class="form-group hidden">
                                            @Html.LabelFor(model => model.IDDiscagemDiretaDistancia, new { @class = "lbdiscagemdiretadistancia control-label col-md-2" })
                                            <div class="col-md-10">
                                                <select id="discagemdiretadistancia" name="idDiscagemdiretadistancia" ajax-url=@Url.Action("List", "DiscagemDiretaDistancia", null, Request.Url.Scheme) value=@Model.IDDiscagemDiretaDistancia></select>
                                                @Html.HiddenFor(model => model.IDDiscagemDiretaDistancia, new { Value = Model.IDDiscagemDiretaDistancia, @id = "valorDiscagemDiretaDistancia" })
                                                @Html.ValidationMessageFor(model => model.IDDiscagemDiretaDistancia)
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.IDLocalidade, new { @class = "lblocalidade control-label col-md-2" })
                                            <div data-ajax-url=@Url.Action("SalvarViaAjax", "Localidade", null, Request.Url.Scheme) id="dadosSalvarLocalidadeViaAjax"></div>
                                            <div class="col-md-10">
                                                <select id="localidade" name="idLocalidade" ajax-url=@Url.Action("ListDropDown", "Localidade", null, Request.Url.Scheme) value=@Model.CodigoIBGE></select>
                                                @Html.HiddenFor(model => model.IDLocalidade, new { Value = Model.CodigoIBGE, @id = "valorIdLocalidade" })
                                                @Html.ValidationMessageFor(model => model.IDLocalidade)
                                            </div>
                                        </div>

                                        <div class="form-group hidden">
                                            @Html.LabelFor(model => model.IDBairro, new { @class = "lbbairro control-label col-md-2" })
                                            <div class="col-md-10">
                                                <select id="bairro" name="idBairro" ajax-url=@Url.Action("List", "Bairro", null, Request.Url.Scheme) value=@Model.IDBairro></select>
                                                @Html.HiddenFor(model => model.IDBairro, new { Value = Model.IDBairro, @id = "valorIdBairro" })
                                                @Html.ValidationMessageFor(model => model.IDBairro)
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Logradouro, new { @class = "lblogradouro control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.Logradouro, new { Value = Model.Logradouro, @id = "logradouro", @class = "logradouro form-control" })
                                                @Html.ValidationMessageFor(model => model.Logradouro)
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Complemento, new { @class = "lbcomplemento control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.Complemento, new { Value = Model.Complemento, @id = "complemento", @class = "complemento form-control" })
                                                @Html.ValidationMessageFor(model => model.Complemento)
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Gia, new { @class = "lbgia control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.Gia, new { @readonly = true, Value = Model.Gia, @id = "gia", @class = "gia form-control" })
                                                @Html.ValidationMessageFor(model => model.Gia)
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Siafi, new { @class = "lbsiafi control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.TextBoxFor(model => model.Siafi, new { @readonly = true, Value = Model.Siafi, @id = "siafi", @class = "siafi form-control" })
                                                @Html.ValidationMessageFor(model => model.Siafi)
                                            </div>
                                        </div>

                                    </div>

                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CepMvcApp.Main/Views/Cep/Index.cshtml
@model IEnumerable<CepMvcApp.Main.Models.CepViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/helpers/url-helpers.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/helpers/dataTables-helpers.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Views/Cep/index.js")"></script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>CEPs</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-12" style="overflow-x: scroll;">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                @{ Html.RenderPartial("~/Views/Toolbars/IndexToolbar.cshtml"); }
            </div>
            <div class="ibox-content">
                <table id="datatable" style="width: 100%;" data-url='@Url.Action("List","Cep")' data-url-edit='@Url.AbsoluteUrlNoController("Form")' data-url-delete='@Url.AbsoluteUrlNoController("Delete")' class="table table-bordered table-hover"></table>
                <div id="datatable-pager"></div>
            </div>
        </div>
    </div>
</div>